export const HELLOONCHAIN_ADDRESS = "0xa238AdEfF7999B453bcAb969DAEbea23646Ccc02" as const;

export const HELLOONCHAIN_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "initialOwner", type: "address" },
      { name: "defaultToken", type: "address" },
      { name: "defaultAmount", type: "uint256" },
      { name: "_dailyClaimCap", type: "uint256" },
      { name: "_cooldownPeriod", type: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "MAX_COOLDOWN",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MIN_COOLDOWN",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "STREAK_WINDOW",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "addRewardToken",
    inputs: [
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "canUserCheckIn",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "canCheckIn", type: "bool" },
      { name: "timeRemaining", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "helloOnchain",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cooldownPeriod",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "currentDayStart",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "dailyClaimCap",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "dailyClaimCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllActiveRewards",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "token", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDailyClaimStats",
    inputs: [],
    outputs: [
      { name: "cap", type: "uint256" },
      { name: "claimed", type: "uint256" },
      { name: "remaining", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRemainingDailyClaims",
    inputs: [],
    outputs: [{ name: "remaining", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRewardTokensCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTokenBalance",
    inputs: [{ name: "token", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserStats",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "firstCheckIn", type: "uint256" },
      { name: "lastCheckIn", type: "uint256" },
      { name: "totalCheckIns", type: "uint256" },
      { name: "currentStreak", type: "uint256" },
      { name: "longestStreak", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isDailyCapReached",
    inputs: [],
    outputs: [{ name: "reached", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "reactivateToken",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeRewardToken",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rewardTokens",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "active", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setCooldownPeriod",
    inputs: [{ name: "_seconds", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setDailyClaimCap",
    inputs: [{ name: "_cap", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateRewardAmount",
    inputs: [
      { name: "index", type: "uint256" },
      { name: "newAmount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "userStats",
    inputs: [{ name: "", type: "address" }],
    outputs: [
      { name: "firstCheckIn", type: "uint256" },
      { name: "lastCheckIn", type: "uint256" },
      { name: "totalCheckIns", type: "uint256" },
      { name: "currentStreak", type: "uint256" },
      { name: "longestStreak", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "willReceiveRewards",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "token", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdrawTokens",
    inputs: [
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "CheckedIn",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "timestamp", type: "uint256", indexed: false },
      { name: "totalCheckIns", type: "uint256", indexed: false },
      { name: "currentStreak", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CooldownPeriodUpdated",
    inputs: [{ name: "newPeriod", type: "uint256", indexed: false }],
  },
  {
    type: "event",
    name: "DailyCapReached",
    inputs: [
      { name: "timestamp", type: "uint256", indexed: false },
      { name: "claimCount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DailyClaimCapUpdated",
    inputs: [{ name: "newCap", type: "uint256", indexed: false }],
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { name: "previousOwner", type: "address", indexed: true },
      { name: "newOwner", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "RewardAmountUpdated",
    inputs: [
      { name: "index", type: "uint256", indexed: true },
      { name: "newAmount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RewardClaimed",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "token", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RewardTokenAdded",
    inputs: [
      { name: "token", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "index", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RewardTokenRemoved",
    inputs: [{ name: "index", type: "uint256", indexed: true }],
  },
  {
    type: "error",
    name: "CooldownNotElapsed",
    inputs: [{ name: "timeRemaining", type: "uint256" }],
  },
  {
    type: "error",
    name: "InvalidCooldown",
    inputs: [
      { name: "provided", type: "uint256" },
      { name: "min", type: "uint256" },
      { name: "max", type: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InvalidTokenIndex",
    inputs: [{ name: "index", type: "uint256" }],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address" }],
  },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address" }],
  },
  {
    type: "error",
    name: "TokenAlreadyExists",
    inputs: [{ name: "token", type: "address" }],
  },
  {
    type: "error",
    name: "TokenNotActive",
    inputs: [{ name: "index", type: "uint256" }],
  },
  {
    type: "error",
    name: "ZeroAddress",
    inputs: [],
  },
  {
    type: "error",
    name: "ZeroAmount",
    inputs: [],
  },
] as const;
